name: Run Tests and Publish Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: mvn test --batch-mode --fail-at-end
    - name: Display test results
      if: always()
      run: cat target/surefire-reports/*.txt
    - name: Publish Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: target/surefire-reports